trigger:
  branches:
    include:
      - master

variables:
  - group: EnvVariables

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npx playwright install
    displayName: 'Install dependencies'

  - script: |
      echo "BASE_URL=$(BASE_URL)" >> .env
      echo "PATIENT_USERNAME=$(PATIENT_USERNAME)" >> .env
      echo "PATIENT_PASSWORD=$(PATIENT_PASSWORD)" >> .env
    displayName: 'Create .env file'

  - script: |
      npm run test || true
    displayName: 'Run tests (continue on failure)'

  - script: |
      echo "Verifying reports directory..."
      ls -R reports/
    displayName: 'Debug: Show reports folder'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'reports/html-report'
      artifactName: 'playwright-report'
      publishLocation: 'Container'
    condition: always()
    displayName: 'Upload HTML Report'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'test-results'
      artifactName: 'playwright-media'
      publishLocation: 'Container'
    condition: always()
    displayName: 'Upload Screenshots & Videos'