trigger:
  branches:
    include:
      - master

variables:
  - group: EnvVariables

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npx playwright install
    displayName: 'Install dependencies'

  - script: |
      echo "BASE_URL=$(BASE_URL)" >> .env
      echo "PATIENT_USERNAME=$(PATIENT_USERNAME)" >> .env
      echo "PATIENT_PASSWORD=$(PATIENT_PASSWORD)" >> .env
    displayName: 'Create .env file'

  - script: |
      npm run test
    displayName: 'Run tests'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'playwright-report'
      artifactName: 'index.html'
      publishLocation: 'Container'
    displayName: 'Publish Playwright HTML Report'